/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cinema.ticket.client.pages;

import com.cinema.ticket.client.api.TicketApi;
import com.cinema.ticket.client.domain.Ticket;

import javax.swing.*;

/**
 * 管理员管理票设置票的信息的窗口
 * @author 22805
 */
public class AdminTicketPage extends javax.swing.JFrame {

    /**
     * 待设置的票数据对象
     */
    private Ticket ticket;

    // 保证只有一个这个对象
    private static final AdminTicketPage adminTicket = new AdminTicketPage();
    public static AdminTicketPage getAdminTicket(Ticket ticket, int x, int y){
        // 设置不可见
        adminTicket.setVisible(false);
        // 设置出现位置
        adminTicket.setLocation(x,y);
        // 设置待更改的票数据对象
        adminTicket.ticket = ticket;
        // 设置票信息的展示
        adminTicket.ticketLabel.setText("该座位坐标位: 第 "+(ticket.getLocX()+1)+" 排, 第 "+(ticket.getLocY()+1)+"列");
        adminTicket.ticketLabel.setVisible(true);
        // 若票没有票ID，则设置相应的属性
        if(ticket.getTicketId()==null){
            // 未出售单选按钮选中
            adminTicket.noSaleRadio.setSelected(true);
            // 设置价格框为空
            adminTicket.priceText.setText("");
        }else{
            // 票有ID
            // 出售单选按钮选中
            adminTicket.saleRadio.setSelected(true);
            // 设置价格
            adminTicket.priceText.setText(ticket.getPrice()+"");
        }
        return adminTicket;
    }

    /**
     * Creates new form AdminTicket
     */
    private AdminTicketPage() {
        // 初始化组件
        initComponents();
        // 设置关闭方式
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        // 设置一直在前
        this.setAlwaysOnTop(true);
        // 设置不可伸缩
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        saleRadio = new javax.swing.JRadioButton();
        noSaleRadio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        priceText = new javax.swing.JTextField();
        confirmBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        ticketLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("是否出售：");

        buttonGroup1.add(saleRadio);
        saleRadio.setText("出售");
        saleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(noSaleRadio);
        noSaleRadio.setText("不出售");
        noSaleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noSaleRadioActionPerformed(evt);
            }
        });

        jLabel2.setText("价格：");

        priceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextActionPerformed(evt);
            }
        });

        confirmBtn.setText("确认");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("取消");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saleRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noSaleRadio))
                            .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(ticketLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(ticketLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(saleRadio)
                    .addComponent(noSaleRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(priceText)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmBtn)
                    .addComponent(cancelBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // 这种没有方法体的方法无用
    private void saleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saleRadioActionPerformed

    private void noSaleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noSaleRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noSaleRadioActionPerformed

    private void priceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextActionPerformed

    // 确认按钮点击方法
    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // TODO add your handling code here:
        // 判断是出售还是不出售
        if(this.saleRadio.isSelected()){
            // 设置票信息
            this.ticket.setPrice(Double.parseDouble(this.priceText.getText()));
            if(ticket.getTicketId()!=null){
                // 判断票是否有ID
                // 有更新
                this.ticketApi.updateTicket(ticket);
            }else{
                // 无删除
                this.ticketApi.insertTicket(ticket);
            }
        }else{
            // 不出售，若票有ID则删除
            if(ticket.getTicketId()!=null){
                this.ticketApi.deleteTicket(ticket.getTicketId());
            }
        }
        // 设置窗口不可见
        this.setVisible(false);
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        // 取消按钮，涉资窗口不可见
        this.setVisible(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    // 发送请求对象
    private final TicketApi ticketApi = new TicketApi();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton noSaleRadio;
    private javax.swing.JTextField priceText;
    private javax.swing.JRadioButton saleRadio;
    private javax.swing.JLabel ticketLabel;
    // End of variables declaration//GEN-END:variables
}
